#!/usr/bin/env python
# encoding: utf-8

"""
Script: stopwords.py
Auteur: PF
Date: 19/04/2021 15:40
"""

# Imports
from nltk.corpus import stopwords

# Functions

s1 = ["a", "à", "â", "lors", "abord", "afin", "ah", "ai", "aie", "ainsi", "allaient", "allo", "allô",
      "allons", "alors", "après", "assez",
      "attendu", "au", "aucun", "aucune", "aucuns", "aujourd", "aujourd'hui", "auquel", "aura", "auront",
      "aussi", "autre", "autres",
      "aux", "auxquelles", "auxquels", "avaient", "avais", "avait", "avant", "avec", "avoir", "ayant", "b",
      "bah", "beaucoup", "bien",
      "bigre", "bon", "boum", "bravo", "brrr", "c", "ça", "car", "ce", "ceci", "cela", "celle", "celle-ci",
      "celle-là", "celles",
      "celles-ci", "celles-là", "celui", "celui-ci", "celui-là", "cent", "cependant", "certain", "certaine",
      "certaines",
      "certains", "certes", "ces", "cet", "cette", "ceux", "ceux-ci", "ceux-là", "chacun", "chaque", "cher",
      "chère", "chères",
      "chers", "chez", "chiche", "chut", "ci", "cinq", "cinquantaine", "cinquante", "cinquantième",
      "cinquième", "clac", "clic",
      "combien", "comme", "comment", "compris", "concernant", "contre", "couic", "crac", "d", "da", "dans",
      "de", "debout", "début",
      "dedans", "dehors", "delà", "depuis", "derrière", "des", "dès", "désormais", "desquelles", "desquels",
      "dessous", "dessus",
      "deux", "deuxième", "deuxièmement", "devant", "devers", "devra", "devrait", "différent", "différente",
      "différentes",
      "différents", "dire", "divers", "diverse", "diverses", "dix", "dix-huit", "dixième", "dix-neuf",
      "dix-sept", "doit",
      "doivent", "donc", "dont", "dos", "douze", "douzième", "dring", "droite", "du", "duquel", "durant",
      "e", "effet", "eh",
      "elle", "elle-même", "elles", "elles-mêmes", "en", "encore", "entre", "envers", "environ", "es", "ès",
      "essai", "est",
      "et", "étaient", "étais", "était", "etant", "étant", "état", "etc", "été", "étions", "etre", "être",
      "eu", "euh", "eux",
      "eux-mêmes", "excepté", "f", "façon", "fais", "faisaient", "faisant", "fait", "faites", "feront",
      "fi", "flac", "floc",
      "fois", "font", "force", "g", "gens", "h", "ha", "haut", "hé", "hein", "hélas", "hem", "hep", "hi",
      "ho", "holà", "hop",
      "hormis", "hors", "hou", "houp", "hue", "hui", "huit", "huitième", "hum", "hurrah", "i", "ici", "il",
      "ils", "importe", "j",
      "je", "jusqu", "jusque", "juste", "k", "l", "la", "là", "laquelle", "las", "le", "lequel", "les",
      "lès", "lesquelles",
      "lesquels", "leur", "leurs", "longtemps", "lorsque", "lui", "lui-même", "m", "ma", "maint",
      "maintenant", "mais",
      "malgré", "me", "même", "mêmes", "merci", "mes", "mien", "mienne", "miennes", "miens", "mille",
      "mince", "mine", "moi",
      "moi-même", "moins", "mon", "mot", "moyennant", "n", "na", "ne", "néanmoins", "neuf", "neuvième",
      "ni", "nombreuses",
      "nombreux", "nommés", "non", "nos", "notre", "nôtre", "nôtres", "nous", "nous-mêmes", "nouveaux",
      "nul", "o", "ô", "o|",
      "oh", "ohé", "olé", "ollé", "on", "ont", "onze", "onzième", "ore", "ou", "où", "ouf", "ouias", "oust",
      "ouste", "outre",
      "p", "paf", "pan", "par", "parce", "parmi", "parole", "partant", "particulier", "particulière",
      "particulièrement",
      "pas", "passé", "pendant", "personne", "personnes", "peu", "peut", "peuvent", "peux", "pff", "pfft",
      "pfut", "pièce",
      "pif", "plein", "plouf", "plupart", "plus", "plusieurs", "plutôt", "pouah", "pour", "pourquoi",
      "premier", "première",
      "premièrement", "près", "proche", "psitt", "puisque", "q", "qu", "quand", "quant", "quanta",
      "quant-à-soi", "quarante",
      "quatorze", "quatre", "quatre-vingt", "quatrième", "quatrièmement", "que", "quel", "quelconque",
      "quelle", "quelles",
      "quelque", "quelques", "quelqu'un", "quels", "qui", "quiconque", "quinze", "quoi", "quoique", "r",
      "revoici", "revoilà",
      "rien", "s", "sa", "sacrebleu", "sans", "sapristi", "sauf", "se", "seize", "selon", "sept",
      "septième", "sera", "seront",
      "ses", "seulement", "si", "sien", "sienne", "siennes", "siens", "sinon", "six", "sixième", "soi",
      "soi-même", "soit",
      "soixante", "son", "sont", "sous", "soyez", "stop", "suis", "suivant", "sujet", "sur", "surtout", "t",
      "ta", "tac", "tandis",
      "tant", "te", "té", "tel", "telle", "tellement", "telles", "tels", "tenant", "tes", "tic", "tien",
      "tienne", "tiennes",
      "tiens", "toc", "toi", "toi-même", "ton", "touchant", "toujours", "tous", "tout", "toute", "toutes",
      "treize", "trente",
      "très", "trois", "troisième", "troisièmement", "trop", "tsoin", "tsouin", "tu", "u", "un", "une",
      "unes", "uns", "v", "va",
      "vais", "valeur", "vas", "vé", "vers", "via", "vif", "vifs", "vingt", "vivat", "vive", "vives",
      "vlan", "voici", "voie",
      "voient", "voilà", "vont", "vos", "votre", "vôtre", "vôtres", "vous", "vous-mêmes", "vu", "w", "x",
      "y", "z", "zut"]

s2 = ["alors",
      "au",
      "aucuns",
      "aussi",
      "autre",
      "avant",
      "avec",
      "avoir",
      "bon",
      "car",
      "ce",
      "cela",
      "ces",
      "ceux",
      "chaque",
      "ci",
      "comme",
      "comment",
      "dans",
      "des",
      "du",
      "de",
      "autour",
      "un",
      "dedans",
      "dehors",
      "depuis",
      "devrait",
      "doit",
      "donc",
      "dos",
      "début",
      "elle",
      "elles",
      "en",
      "encore",
      "essai",
      "est",
      "et",
      "eu",
      "fait",
      "faites",
      "fois",
      "font",
      "hors",
      "ici",
      "il",
      "ils",
      "je",
      "juste",
      "la",
      "le",
      "les",
      "leur",
      "là",
      "ma",
      "maintenant",
      "mais",
      "mes",
      "mine",
      "moins",
      "mon",
      "mot",
      "même",
      "ni",
      "nommés",
      "notre",
      "nous",
      "ou",
      "où",
      "par",
      "parce",
      "pas",
      "peut",
      "peu",
      "plupart",
      "pour",
      "pourquoi",
      "quand",
      "que",
      "quel",
      "quelle",
      "quelles",
      "quels",
      "qui",
      "sa",
      "sans",
      "ses",
      "seulement",
      "si",
      "sien",
      "son",
      "sont",
      "sous",
      "soyez",
      "sur",
      "ta",
      "tandis",
      "tellement",
      "tels",
      "tes",
      "ton",
      "tous",
      "tout",
      "trop",
      "très",
      "tu",
      "voient",
      "vont",
      "votre",
      "vous",
      "vu",
      "ça",
      "étaient",
      "état",
      "étions",
      "été",
      "être"]


def custom_fr_stopwords():
    return set(stopwords.words('french') + s1 + s2)


# Main
def main():
    pass


if __name__ == '__main__':
    main()
